### ISSUE TITLE
Replace command-line-args, command-line-commands and command-line-usage with yargs

### ISSUE THREAD

**Issue by frederikschubert** [INSIDEM2M/slim#38]
`yargs` already does all the things the three libraries are doing with an easier to use API. We should switch to `yargs` to reduce dependencies.
See http://blog.npmjs.org/post/119317128765/adding-subcommands-to-your-command-line-tool for an example.

**Comment by frederikschubert** [comment]
Through this we can also install all typescript typings via yarn and can delete the `typings.json` file.

**Comment by 0xE282B0** [comment]
I'm fine with `yargs`.
