### ISSUE TITLE
yarn.lock file in dev branch

### ISSUE THREAD

**Issue by 0xE282B0** [INSIDEM2M/slim#76]
Is the yarn.lock file necessary in development branch?
It's a source of merge conflicts.

**Comment by frederikschubert** [comment]
It might be possible to remove it from develop but afaik it is not possible to add a file to only one branch. We would have to investigate how it can be excluded.

**Comment by frederikschubert** [comment]
We can use the approach described [here](https://stackoverflow.com/questions/1836742/using-git-how-do-i-ignore-a-file-in-one-branch-but-have-it-committed-in-another).
